<<<<<<< HEAD
<<<<<<< HEAD
name: generative-ai
channels:
 - defaults
dependencies:
- python=3.11.4
- openai
- python-dotenv
=======
name: <environment-name>
=======
name: dev
>>>>>>> b88b09e22d023505eb4b289b4b85fe9f42c33293
channels:
 - defaults
dependencies:
- python=3.10.0
- openai
- python-dotenv
- pip
- pip:
  - azure-ai-inference
>>>>>>> 72567820ac066161f141652a43b1940e09af7756
